// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/okocraft/monitor/internal/config"
	"github.com/okocraft/monitor/internal/handler"
	auditlog3 "github.com/okocraft/monitor/internal/handler/auditlog"
	auth3 "github.com/okocraft/monitor/internal/handler/oapi/auth"
	"github.com/okocraft/monitor/internal/handler/oapi/me"
	role3 "github.com/okocraft/monitor/internal/handler/oapi/role"
	user3 "github.com/okocraft/monitor/internal/handler/oapi/user"
	"github.com/okocraft/monitor/internal/repositories/auditlog"
	"github.com/okocraft/monitor/internal/repositories/auth"
	"github.com/okocraft/monitor/internal/repositories/database"
	"github.com/okocraft/monitor/internal/repositories/permission"
	"github.com/okocraft/monitor/internal/repositories/role"
	"github.com/okocraft/monitor/internal/repositories/user"
	auditlog2 "github.com/okocraft/monitor/internal/usecases/auditlog"
	auth2 "github.com/okocraft/monitor/internal/usecases/auth"
	"github.com/okocraft/monitor/internal/usecases/cleanup"
	permission2 "github.com/okocraft/monitor/internal/usecases/permission"
	role2 "github.com/okocraft/monitor/internal/usecases/role"
	"github.com/okocraft/monitor/internal/usecases/setup"
	user2 "github.com/okocraft/monitor/internal/usecases/user"
)

// Injectors from wire.go:

func NewHTTPHandler(cfg config.HTTPServerConfig, db database.DB) (handler.HTTPHandler, error) {
	authConfig := getAuthConfigFromHTTPConfig(cfg)
	authRepository := auth.NewAuthRepository(db)
	authUsecase := auth2.NewAuthUsecase(authConfig, authRepository)
	userRepository := user.NewUserRepository(db)
	transaction := database.NewTransaction(db)
	userUsecase := user2.NewUserUsecase(userRepository, transaction)
	permissionRepository := permission.NewPermissionRepository(db)
	permissionUsecase := permission2.NewPermissionUsecase(permissionRepository)
	authHandler := auth3.NewAuthHandler(authUsecase, userUsecase, permissionUsecase)
	googleAuthConfig := getGoogleAuthConfigFromHTTPConfig(cfg)
	googleAuthHandler := auth3.NewGoogleAuthHandler(googleAuthConfig, authUsecase, userUsecase)
	meHandler := me.NewMeHandler(userUsecase)
	roleRepository := role.NewRoleRepository(db)
	roleUsecase := role2.NewRoleUsecase(roleRepository)
	roleHandler := role3.NewRoleHandler(roleUsecase, permissionUsecase)
	userHandler := user3.NewUserHandler(userUsecase, permissionUsecase)
	auditLogRepository := auditlog.NewAuditLogRepository(db)
	auditLogUsecase := auditlog2.NewAuditLogUsecase(auditLogRepository)
	auditLogMiddleware := auditlog3.NewAuditLogMiddleware(auditLogUsecase, userUsecase)
	httpHandler := handler.NewHTTPHandler(authHandler, googleAuthHandler, meHandler, roleHandler, userHandler, auditLogMiddleware)
	return httpHandler, nil
}

func NewCleanupUsecase(db database.DB) cleanup.CleanupUsecase {
	authRepository := auth.NewAuthRepository(db)
	transaction := database.NewTransaction(db)
	cleanupUsecase := cleanup.NewCleanupUsecase(authRepository, transaction)
	return cleanupUsecase
}

func NewSetupUsecase(db database.DB) setup.SetupUsecase {
	roleRepository := role.NewRoleRepository(db)
	userRepository := user.NewUserRepository(db)
	permissionRepository := permission.NewPermissionRepository(db)
	setupUsecase := setup.NewSetupUsecase(roleRepository, userRepository, permissionRepository)
	return setupUsecase
}

func NewTransaction(db database.DB) database.Transaction {
	transaction := database.NewTransaction(db)
	return transaction
}
