// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/okocraft/monitor/internal/handler/oapi"
)

// Injectors from wire.go:

func NewHTTPHandler() (oapi.HTTPHandler, error) {
	pingHandler := oapi.NewPingHandler()
	httpHandler := oapi.NewHTTPHandler(pingHandler)
	return httpHandler, nil
}
