/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */

import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type { SearchUsersParams, User, Uuid } from "../model";

/**
 * get users by ids
 */
export type getUsersByIdsResponse200 = {
    data: User[];
    status: 200;
};

export type getUsersByIdsResponse400 = {
    data: void;
    status: 400;
};

export type getUsersByIdsResponse404 = {
    data: void;
    status: 404;
};

export type getUsersByIdsResponseSuccess = getUsersByIdsResponse200 & {
    headers: Headers;
};
export type getUsersByIdsResponseError = (
    | getUsersByIdsResponse400
    | getUsersByIdsResponse404
) & {
    headers: Headers;
};

export type getUsersByIdsResponse =
    | getUsersByIdsResponseSuccess
    | getUsersByIdsResponseError;

export const getGetUsersByIdsUrl = () => {
    return `/users`;
};

export const getUsersByIds = async (
    uuid: Uuid[],
    options?: RequestInit,
): Promise<getUsersByIdsResponse> => {
    const res = await fetch(getGetUsersByIdsUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(uuid),
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getUsersByIdsResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as getUsersByIdsResponse;
};

export const getGetUsersByIdsMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof getUsersByIds>>,
        TError,
        { data: Uuid[] },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof getUsersByIds>>,
    TError,
    { data: Uuid[] },
    TContext
> => {
    const mutationKey = ["getUsersByIds"];
    const { mutation: mutationOptions, fetch: fetchOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof getUsersByIds>>,
        { data: Uuid[] }
    > = (props) => {
        const { data } = props ?? {};

        return getUsersByIds(data, fetchOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type GetUsersByIdsMutationResult = NonNullable<
    Awaited<ReturnType<typeof getUsersByIds>>
>;
export type GetUsersByIdsMutationBody = Uuid[];
export type GetUsersByIdsMutationError = void;

export const useGetUsersByIds = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof getUsersByIds>>,
            TError,
            { data: Uuid[] },
            TContext
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof getUsersByIds>>,
    TError,
    { data: Uuid[] },
    TContext
> => {
    return useMutation(getGetUsersByIdsMutationOptions(options), queryClient);
};
/**
 * get user ids
 */
export type searchUsersResponse200 = {
    data: Uuid[];
    status: 200;
};

export type searchUsersResponseSuccess = searchUsersResponse200 & {
    headers: Headers;
};

export type searchUsersResponse = searchUsersResponseSuccess;

export const getSearchUsersUrl = (params?: SearchUsersParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString(),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/users/search?${stringifiedParams}`
        : `/users/search`;
};

export const searchUsers = async (
    params?: SearchUsersParams,
    options?: RequestInit,
): Promise<searchUsersResponse> => {
    const res = await fetch(getSearchUsersUrl(params), {
        ...options,
        method: "GET",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: searchUsersResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as searchUsersResponse;
};

export const getSearchUsersQueryKey = (params?: SearchUsersParams) => {
    return [`/users/search`, ...(params ? [params] : [])] as const;
};

export const getSearchUsersQueryOptions = <
    TData = Awaited<ReturnType<typeof searchUsers>>,
    TError = unknown,
>(
    params?: SearchUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchUsers>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
    },
) => {
    const { query: queryOptions, fetch: fetchOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getSearchUsersQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof searchUsers>>> = ({
        signal,
    }) => searchUsers(params, { signal, ...fetchOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof searchUsers>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SearchUsersQueryResult = NonNullable<
    Awaited<ReturnType<typeof searchUsers>>
>;
export type SearchUsersQueryError = unknown;

export function useSearchUsers<
    TData = Awaited<ReturnType<typeof searchUsers>>,
    TError = unknown,
>(
    params: undefined | SearchUsersParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchUsers>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof searchUsers>>,
                    TError,
                    Awaited<ReturnType<typeof searchUsers>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchUsers<
    TData = Awaited<ReturnType<typeof searchUsers>>,
    TError = unknown,
>(
    params?: SearchUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchUsers>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof searchUsers>>,
                    TError,
                    Awaited<ReturnType<typeof searchUsers>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSearchUsers<
    TData = Awaited<ReturnType<typeof searchUsers>>,
    TError = unknown,
>(
    params?: SearchUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchUsers>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useSearchUsers<
    TData = Awaited<ReturnType<typeof searchUsers>>,
    TError = unknown,
>(
    params?: SearchUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof searchUsers>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getSearchUsersQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}
