/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */

import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";
import { useQuery } from "@tanstack/react-query";

import type { GetRolesParams, Role } from "../model";

/**
 * get all roles
 */
export type getRolesResponse200 = {
    data: Role[];
    status: 200;
};

export type getRolesResponseSuccess = getRolesResponse200 & {
    headers: Headers;
};

export type getRolesResponse = getRolesResponseSuccess;

export const getGetRolesUrl = (params?: GetRolesParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString(),
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/roles?${stringifiedParams}`
        : `/roles`;
};

export const getRoles = async (
    params?: GetRolesParams,
    options?: RequestInit,
): Promise<getRolesResponse> => {
    const res = await fetch(getGetRolesUrl(params), {
        ...options,
        method: "GET",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: getRolesResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as getRolesResponse;
};

export const getGetRolesQueryKey = (params?: GetRolesParams) => {
    return [`/roles`, ...(params ? [params] : [])] as const;
};

export const getGetRolesQueryOptions = <
    TData = Awaited<ReturnType<typeof getRoles>>,
    TError = unknown,
>(
    params?: GetRolesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
        >;
        fetch?: RequestInit;
    },
) => {
    const { query: queryOptions, fetch: fetchOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetRolesQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRoles>>> = ({
        signal,
    }) => getRoles(params, { signal, ...fetchOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getRoles>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRolesQueryResult = NonNullable<
    Awaited<ReturnType<typeof getRoles>>
>;
export type GetRolesQueryError = unknown;

export function useGetRoles<
    TData = Awaited<ReturnType<typeof getRoles>>,
    TError = unknown,
>(
    params: undefined | GetRolesParams,
    options: {
        query: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRoles>>,
                    TError,
                    Awaited<ReturnType<typeof getRoles>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRoles<
    TData = Awaited<ReturnType<typeof getRoles>>,
    TError = unknown,
>(
    params?: GetRolesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRoles>>,
                    TError,
                    Awaited<ReturnType<typeof getRoles>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRoles<
    TData = Awaited<ReturnType<typeof getRoles>>,
    TError = unknown,
>(
    params?: GetRolesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetRoles<
    TData = Awaited<ReturnType<typeof getRoles>>,
    TError = unknown,
>(
    params?: GetRolesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<Awaited<ReturnType<typeof getRoles>>, TError, TData>
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetRolesQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}
