openapi: 3.0.0
info:
  title: Monitor API
  version: 0.0.0
tags:
  - name: Auth
  - name: Me
paths:
  /auth/google/callback:
    get:
      operationId: callbackFromGoogle
      description: Callback from Google
      parameters: []
      responses:
        '307':
          description: Redirection
        '406':
          description: Client error
      tags:
        - Auth
      security:
        - SkipAuth: []
  /auth/google/link/{loginKey}:
    post:
      operationId: linkWithGoogle
      description: First login with Google Account
      parameters:
        - name: loginKey
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleLoginURL'
        '406':
          description: Client error
      tags:
        - Auth
      security:
        - SkipAuth: []
  /auth/google/login:
    post:
      operationId: loginWithGoogle
      description: Login with Google Account
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleLoginURL'
        '406':
          description: Client error
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CurrentPage'
      security:
        - SkipAuth: []
  /auth/logout:
    post:
      operationId: logout
      description: Invalidate refresh_token and access_token
      parameters: []
      responses:
        '204':
          description: 'There is no content to send for this request, but the headers may be useful. '
        '401':
          description: Access is unauthorized.
      tags:
        - Auth
      security:
        - SkipAuth: []
  /auth/refresh:
    post:
      operationId: refreshAccessToken
      description: Refresh access token
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenWithMe'
        '401':
          description: Access is unauthorized.
      tags:
        - Auth
      security:
        - SkipAuth: []
  /me:
    get:
      operationId: getMe
      description: get own user info
      parameters: []
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Me'
      tags:
        - Me
security:
  - AccessTokenAuth: []
components:
  schemas:
    AccessTokenWithMe:
      type: object
      required:
        - access_token
        - me
      properties:
        access_token:
          type: string
          description: the access token
        me:
          allOf:
            - $ref: '#/components/schemas/Me'
          description: the currently logged-in user info
    CurrentPage:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          format: url
          description: the url of the page currently being viewed
    GoogleLoginURL:
      type: object
      required:
        - redirect_url
      properties:
        redirect_url:
          type: string
          format: url
          description: the Google's login page URL
    Me:
      type: object
      required:
        - uuid
        - nickname
      properties:
        uuid:
          $ref: '#/components/schemas/UUID'
        nickname:
          type: string
    UUID:
      type: string
      format: uuid
      description: the UUID
      x-go-type-import:
        name: uuid
        path: github.com/gofrs/uuid/v5
      x-go-type: uuid.UUID
  securitySchemes:
    AccessTokenAuth:
      type: http
      scheme: bearer
      description: Authorize by access tokens
    SkipAuth:
      type: http
      scheme: none
      description: No authentication needed
