# yaml-language-server: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/schemas/v3.0/schema.json
openapi: "3.0.0"
info:
  version: 0.0.1
  title: Monitor API

tags:
  - name: Auth
  - name: Me

paths:
  /auth/logout:
    post:
      operationId: logout
      description: Invalidate refresh_token and access_token
      tags:
        - Auth
      responses:
        204:
          description: ok
        401:
          description: invalid refresh token
      security:
        - SkipAuth: [ ]
  /auth/google/link/{login_key}:
    parameters:
      - name: login_key
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: linkWithGoogle
      description: First login with Google Account
      tags:
        - Auth
      responses:
        200:
          description: the url of Google's account page
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleLoginURL'
        406:
          description: if Google login is not enabled
      security:
        - SkipAuth: [ ]
  /auth/google/login:
    post:
      operationId: loginWithGoogle
      description: Login with Google Account
      tags:
        - Auth
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CurrentPage'
      responses:
        200:
          description: the url of Google's account page
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleLoginURL'
        406:
          description: if Google login is not enabled
      security:
        - SkipAuth: [ ]
  /auth/google/callback:
    get:
      operationId: callbackFromGoogle
      description: Callback from Google
      tags:
        - Auth
      responses:
        307:
          description: redirect to monitor page
        406:
          description: if Google login is not enabled
      security:
        - SkipAuth: [ ]
  /auth/refresh:
    post:
      operationId: refreshAccessToken
      description: Refresh access token
      tags:
        - Auth
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessTokenWithMe'
      security:
        - SkipAuth: [ ]

  /me:
    get:
      operationId: getMe
      description: get own user info
      tags:
        - Me
      responses:
        200:
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Me'

components:
  schemas:
    AccessTokenWithMe:
        properties:
          access_token:
            type: string
            description: the access token
          me:
            $ref: '#/components/schemas/Me'
        required:
          - access_token
          - me
    UUID:
      type: string
      description: the UUID
      format: uuid
      x-go-type: uuid.UUID
      x-go-type-import:
        name: uuid
        path: github.com/gofrs/uuid/v5
    Me:
      properties:
        uuid:
          $ref: '#/components/schemas/UUID'
        nickname:
          type: string
      required:
        - uuid
        - nickname

    GoogleLoginURL:
      properties:
        redirect_url:
          type: string
          format: url
      required:
        - redirect_url

    CurrentPage:
      properties:
        url:
          type: string
          format: url
      required:
        - url

  securitySchemes:
    SkipAuth:
      type: http
      scheme: none
    AccessTokenAuth:
      type: http
      scheme: bearer

security:
  - AccessTokenAuth: [ ]
