// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: audit_log.sql

package queries

import (
	"context"
	"database/sql"
	"time"
)

const insertOperator = `-- name: InsertOperator :execresult
INSERT INTO audit_log_operators (user_id, name, ip, created_at)
VALUES (?, ?, ?, ?)
`

type InsertOperatorParams struct {
	UserID    int32     `db:"user_id"`
	Name      string    `db:"name"`
	Ip        []byte    `db:"ip"`
	CreatedAt time.Time `db:"created_at"`
}

func (q *Queries) InsertOperator(ctx context.Context, arg InsertOperatorParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertOperator,
		arg.UserID,
		arg.Name,
		arg.Ip,
		arg.CreatedAt,
	)
}
