// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package queries

import (
	"context"
	"time"
)

const deleteAccessTokensByExpiredRefreshTokens = `-- name: DeleteAccessTokensByExpiredRefreshTokens :execrows
DELETE
FROM users_access_tokens
WHERE refresh_token_id IN (SELECT users_refresh_tokens.created_at
                           FROM users_refresh_tokens
                           WHERE users_refresh_tokens.created_at < ?)
`

func (q *Queries) DeleteAccessTokensByExpiredRefreshTokens(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAccessTokensByExpiredRefreshTokens, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredAccessTokens = `-- name: DeleteExpiredAccessTokens :execrows
DELETE
FROM users_access_tokens
WHERE created_at < ?
`

func (q *Queries) DeleteExpiredAccessTokens(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredAccessTokens, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :execrows
DELETE
FROM users_refresh_tokens
WHERE created_at < ?
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context, createdAt time.Time) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredRefreshTokens, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRefreshTokenAndAccessToken = `-- name: DeleteRefreshTokenAndAccessToken :exec
DELETE
FROM users_refresh_tokens
WHERE id = ?
`

func (q *Queries) DeleteRefreshTokenAndAccessToken(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRefreshTokenAndAccessToken, id)
	return err
}

const getUserIDAndRefreshTokenIDByJTI = `-- name: GetUserIDAndRefreshTokenIDByJTI :one
SELECT id, user_id
FROM users_refresh_tokens
WHERE jti = ?
`

type GetUserIDAndRefreshTokenIDByJTIRow struct {
	ID     int64 `db:"id"`
	UserID int32 `db:"user_id"`
}

func (q *Queries) GetUserIDAndRefreshTokenIDByJTI(ctx context.Context, jti []byte) (GetUserIDAndRefreshTokenIDByJTIRow, error) {
	row := q.db.QueryRowContext(ctx, getUserIDAndRefreshTokenIDByJTI, jti)
	var i GetUserIDAndRefreshTokenIDByJTIRow
	err := row.Scan(&i.ID, &i.UserID)
	return i, err
}

const getUserIDByAccessTokenJTI = `-- name: GetUserIDByAccessTokenJTI :one
SELECT user_id
FROM users_access_tokens
WHERE jti = ?
`

func (q *Queries) GetUserIDByAccessTokenJTI(ctx context.Context, jti []byte) (int32, error) {
	row := q.db.QueryRowContext(ctx, getUserIDByAccessTokenJTI, jti)
	var user_id int32
	err := row.Scan(&user_id)
	return user_id, err
}

const insertAccessToken = `-- name: InsertAccessToken :exec
INSERT INTO users_access_tokens (user_id, refresh_token_id, jti, created_at)
VALUES (?, ?, ?, ?)
`

type InsertAccessTokenParams struct {
	UserID         int32     `db:"user_id"`
	RefreshTokenID int64     `db:"refresh_token_id"`
	Jti            []byte    `db:"jti"`
	CreatedAt      time.Time `db:"created_at"`
}

func (q *Queries) InsertAccessToken(ctx context.Context, arg InsertAccessTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertAccessToken,
		arg.UserID,
		arg.RefreshTokenID,
		arg.Jti,
		arg.CreatedAt,
	)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO users_refresh_tokens (user_id, jti, ip, user_agent, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertRefreshTokenParams struct {
	UserID    int32     `db:"user_id"`
	Jti       []byte    `db:"jti"`
	Ip        []byte    `db:"ip"`
	UserAgent string    `db:"user_agent"`
	CreatedAt time.Time `db:"created_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, insertRefreshToken,
		arg.UserID,
		arg.Jti,
		arg.Ip,
		arg.UserAgent,
		arg.CreatedAt,
	)
	return err
}
