// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package queries

import (
	"time"
)

type User struct {
	ID         int32
	Uuid       []byte
	Nickname   string
	LastAccess time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type UsersAccessToken struct {
	ID             int64
	UserID         int32
	RefreshTokenID int64
	Jti            []byte
	CreatedAt      time.Time
}

type UsersLoginKey struct {
	UserID    int32
	LoginKey  int64
	CreatedAt time.Time
}

type UsersRefreshToken struct {
	ID        int64
	UserID    int32
	Jti       []byte
	Ip        []byte
	UserAgent string
	CreatedAt time.Time
}

type UsersSession struct {
	ID        int64
	UserID    int32
	SessionID []byte
	CreatedAt time.Time
}

type UsersSub struct {
	UserID int32
	Sub    string
}
