// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: permission_test.sql

package queries

import (
	"context"
)

const insertPermissionForTest = `-- name: InsertPermissionForTest :exec
INSERT INTO roles_permissions (role_id, permission_id, is_allowed)
VALUES (?, ?, ?)
`

type InsertPermissionForTestParams struct {
	RoleID       int32 `db:"role_id"`
	PermissionID int16 `db:"permission_id"`
	IsAllowed    bool  `db:"is_allowed"`
}

func (q *Queries) InsertPermissionForTest(ctx context.Context, arg InsertPermissionForTestParams) error {
	_, err := q.db.ExecContext(ctx, insertPermissionForTest, arg.RoleID, arg.PermissionID, arg.IsAllowed)
	return err
}
