// Code generated by go-tablelist-codegen. DO NOT EDIT.

package queries

var AuditLogOperatorsTable = struct {
    TableName string
    Id string
    UserId string
    Name string
    Ip string
    CreatedAt string
}{
    TableName: "audit_log_operators",
    Id: "id",
    UserId: "user_id",
    Name: "name",
    Ip: "ip",
    CreatedAt: "created_at",
}

var AuditLogUserTable = struct {
    TableName string
    Id string
    OperatorId string
    ActionType string
    ChangedFrom string
    ChangedTo string
    CreatedAt string
}{
    TableName: "audit_log_user",
    Id: "id",
    OperatorId: "operator_id",
    ActionType: "action_type",
    ChangedFrom: "changed_from",
    ChangedTo: "changed_to",
    CreatedAt: "created_at",
}

var RolesTable = struct {
    TableName string
    Id string
    Uuid string
    Name string
    Priority string
    CreatedAt string
    UpdatedAt string
}{
    TableName: "roles",
    Id: "id",
    Uuid: "uuid",
    Name: "name",
    Priority: "priority",
    CreatedAt: "created_at",
    UpdatedAt: "updated_at",
}

var RolesPermissionsTable = struct {
    TableName string
    RoleId string
    PermissionId string
    IsAllowed string
}{
    TableName: "roles_permissions",
    RoleId: "role_id",
    PermissionId: "permission_id",
    IsAllowed: "is_allowed",
}

var UsersTable = struct {
    TableName string
    Id string
    Uuid string
    Nickname string
    LastAccess string
    CreatedAt string
    UpdatedAt string
}{
    TableName: "users",
    Id: "id",
    Uuid: "uuid",
    Nickname: "nickname",
    LastAccess: "last_access",
    CreatedAt: "created_at",
    UpdatedAt: "updated_at",
}

var UsersAccessTokensTable = struct {
    TableName string
    Id string
    UserId string
    RefreshTokenId string
    Jti string
    CreatedAt string
}{
    TableName: "users_access_tokens",
    Id: "id",
    UserId: "user_id",
    RefreshTokenId: "refresh_token_id",
    Jti: "jti",
    CreatedAt: "created_at",
}

var UsersLoginKeyTable = struct {
    TableName string
    UserId string
    LoginKey string
    CreatedAt string
}{
    TableName: "users_login_key",
    UserId: "user_id",
    LoginKey: "login_key",
    CreatedAt: "created_at",
}

var UsersRefreshTokensTable = struct {
    TableName string
    Id string
    UserId string
    Jti string
    Ip string
    UserAgent string
    CreatedAt string
}{
    TableName: "users_refresh_tokens",
    Id: "id",
    UserId: "user_id",
    Jti: "jti",
    Ip: "ip",
    UserAgent: "user_agent",
    CreatedAt: "created_at",
}

var UsersRoleTable = struct {
    TableName string
    UserId string
    RoleId string
    UpdatedAt string
}{
    TableName: "users_role",
    UserId: "user_id",
    RoleId: "role_id",
    UpdatedAt: "updated_at",
}

var UsersSubTable = struct {
    TableName string
    UserId string
    Sub string
}{
    TableName: "users_sub",
    UserId: "user_id",
    Sub: "sub",
}
