// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: user_test.sql

package queries

import (
	"context"
	"time"
)

const insertUserWithIDForTest = `-- name: InsertUserWithIDForTest :exec
INSERT INTO users (id, uuid, nickname, last_access, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertUserWithIDForTestParams struct {
	ID         int32     `db:"id"`
	Uuid       []byte    `db:"uuid"`
	Nickname   string    `db:"nickname"`
	LastAccess time.Time `db:"last_access"`
	CreatedAt  time.Time `db:"created_at"`
	UpdatedAt  time.Time `db:"updated_at"`
}

func (q *Queries) InsertUserWithIDForTest(ctx context.Context, arg InsertUserWithIDForTestParams) error {
	_, err := q.db.ExecContext(ctx, insertUserWithIDForTest,
		arg.ID,
		arg.Uuid,
		arg.Nickname,
		arg.LastAccess,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
