// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_test.sql

package queries

import (
	"context"
	"time"
)

const insertUserWithIDForTest = `-- name: InsertUserWithIDForTest :exec
INSERT INTO users (id, uuid, nickname, last_access, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertUserWithIDForTestParams struct {
	ID         int32
	Uuid       []byte
	Nickname   string
	LastAccess time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

func (q *Queries) InsertUserWithIDForTest(ctx context.Context, arg InsertUserWithIDForTestParams) error {
	_, err := q.db.ExecContext(ctx, insertUserWithIDForTest,
		arg.ID,
		arg.Uuid,
		arg.Nickname,
		arg.LastAccess,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
