/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: afb1c7e7cb461198cf0be317e85b5534)
interface __BaseEnv_Env {
	MONITOR_OBJECT_BUCKET: R2Bucket;
	SECRET_KEY: string;
	DEBUG: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
