/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as MypageIndexRouteImport } from './routes/mypage/index'
import { Route as ExampleIndexRouteImport } from './routes/example/index'
import { Route as SettingsUsersIndexRouteImport } from './routes/settings/users/index'
import { Route as SettingsRolesIndexRouteImport } from './routes/settings/roles/index'
import { Route as GoogleResultIndexRouteImport } from './routes/google/result/index'
import { Route as GoogleLoginIndexRouteImport } from './routes/google/login/index'
import { Route as GoogleLinkIndexRouteImport } from './routes/google/link/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const MypageIndexRoute = MypageIndexRouteImport.update({
  id: '/mypage/',
  path: '/mypage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleIndexRoute = ExampleIndexRouteImport.update({
  id: '/example/',
  path: '/example/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersIndexRoute = SettingsUsersIndexRouteImport.update({
  id: '/settings/users/',
  path: '/settings/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesIndexRoute = SettingsRolesIndexRouteImport.update({
  id: '/settings/roles/',
  path: '/settings/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleResultIndexRoute = GoogleResultIndexRouteImport.update({
  id: '/google/result/',
  path: '/google/result/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleLoginIndexRoute = GoogleLoginIndexRouteImport.update({
  id: '/google/login/',
  path: '/google/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleLinkIndexRoute = GoogleLinkIndexRouteImport.update({
  id: '/google/link/',
  path: '/google/link/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example': typeof ExampleIndexRoute
  '/mypage': typeof MypageIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/google/link': typeof GoogleLinkIndexRoute
  '/google/login': typeof GoogleLoginIndexRoute
  '/google/result': typeof GoogleResultIndexRoute
  '/settings/roles': typeof SettingsRolesIndexRoute
  '/settings/users': typeof SettingsUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example': typeof ExampleIndexRoute
  '/mypage': typeof MypageIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/google/link': typeof GoogleLinkIndexRoute
  '/google/login': typeof GoogleLoginIndexRoute
  '/google/result': typeof GoogleResultIndexRoute
  '/settings/roles': typeof SettingsRolesIndexRoute
  '/settings/users': typeof SettingsUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/example/': typeof ExampleIndexRoute
  '/mypage/': typeof MypageIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/google/link/': typeof GoogleLinkIndexRoute
  '/google/login/': typeof GoogleLoginIndexRoute
  '/google/result/': typeof GoogleResultIndexRoute
  '/settings/roles/': typeof SettingsRolesIndexRoute
  '/settings/users/': typeof SettingsUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/example'
    | '/mypage'
    | '/settings'
    | '/google/link'
    | '/google/login'
    | '/google/result'
    | '/settings/roles'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/example'
    | '/mypage'
    | '/settings'
    | '/google/link'
    | '/google/login'
    | '/google/result'
    | '/settings/roles'
    | '/settings/users'
  id:
    | '__root__'
    | '/'
    | '/example/'
    | '/mypage/'
    | '/settings/'
    | '/google/link/'
    | '/google/login/'
    | '/google/result/'
    | '/settings/roles/'
    | '/settings/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExampleIndexRoute: typeof ExampleIndexRoute
  MypageIndexRoute: typeof MypageIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  GoogleLinkIndexRoute: typeof GoogleLinkIndexRoute
  GoogleLoginIndexRoute: typeof GoogleLoginIndexRoute
  GoogleResultIndexRoute: typeof GoogleResultIndexRoute
  SettingsRolesIndexRoute: typeof SettingsRolesIndexRoute
  SettingsUsersIndexRoute: typeof SettingsUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mypage/': {
      id: '/mypage/'
      path: '/mypage'
      fullPath: '/mypage'
      preLoaderRoute: typeof MypageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/': {
      id: '/example/'
      path: '/example'
      fullPath: '/example'
      preLoaderRoute: typeof ExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users/': {
      id: '/settings/users/'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles/': {
      id: '/settings/roles/'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google/result/': {
      id: '/google/result/'
      path: '/google/result'
      fullPath: '/google/result'
      preLoaderRoute: typeof GoogleResultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google/login/': {
      id: '/google/login/'
      path: '/google/login'
      fullPath: '/google/login'
      preLoaderRoute: typeof GoogleLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google/link/': {
      id: '/google/link/'
      path: '/google/link'
      fullPath: '/google/link'
      preLoaderRoute: typeof GoogleLinkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExampleIndexRoute: ExampleIndexRoute,
  MypageIndexRoute: MypageIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  GoogleLinkIndexRoute: GoogleLinkIndexRoute,
  GoogleLoginIndexRoute: GoogleLoginIndexRoute,
  GoogleResultIndexRoute: GoogleResultIndexRoute,
  SettingsRolesIndexRoute: SettingsRolesIndexRoute,
  SettingsUsersIndexRoute: SettingsUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
