/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */
import type { Me } from "./me";

export interface AccessTokenWithMe {
    /** the access token */
    access_token: string;
    /** the currently logged-in user info */
    me: Me;
}
