/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */

export interface CurrentPage {
    /** the url of the page currently being viewed */
    url: string;
}
