/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */
import type { SortableRoleDataType } from "./sortableRoleDataType";
import type { SortType } from "./sortType";

export type GetRolesParams = {
    sorted_by?: SortableRoleDataType;
    sort_type?: SortType;
};
