/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */

export interface GoogleLoginURL {
    /** the Google's login page URL */
    redirect_url: string;
}
