/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */
import type { Uuid } from "./uuid";

export interface Me {
    uuid: Uuid;
    nickname: string;
    role_uuid: Uuid;
    role_name: string;
}
