/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.1
 */
import type { Uuid } from './uuid';

export interface Me {
  nickname: string;
  uuid: Uuid;
}
