/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */
import type { SettingPagePermissions } from "./settingPagePermissions";

export interface PagePermissions {
    settings: SettingPagePermissions;
}
