/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */
import type { SettingPagePermissions } from "./settingPagePermissions";

export interface PagePermissions {
    settings: SettingPagePermissions;
}
