/**
 * Generated by orval v7.3.0 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.1
 */

export interface Pong {
  /** the message */
  message: string;
  /** the name */
  name: string;
}
