/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */

export interface Role {
    id: number;
    name: string;
    priority: number;
    created_at: string;
    updated_at: string;
}
