/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */
import type { SortableUserDataType } from "./sortableUserDataType";
import type { SortType } from "./sortType";
import type { Uuid } from "./uuid";

export type SearchUsersParams = {
    nickname?: string;
    last_access_before?: string;
    last_access_after?: string;
    role_id?: Uuid;
    sorted_by?: SortableUserDataType;
    sort_type?: SortType;
};
