/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */

export type SortType = (typeof SortType)[keyof typeof SortType];

export const SortType = {
    ASC: "ASC",
    DESC: "DESC",
} as const;
