/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */

export type SortableRoleDataType =
    (typeof SortableRoleDataType)[keyof typeof SortableRoleDataType];

export const SortableRoleDataType = {
    Name: "Name",
    Priority: "Priority",
    CreatedAt: "CreatedAt",
    UpdatedAt: "UpdatedAt",
} as const;
