/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */

export type SortableUserDataType =
    (typeof SortableUserDataType)[keyof typeof SortableUserDataType];

export const SortableUserDataType = {
    NickName: "NickName",
    LastAccess: "LastAccess",
    CreatedAt: "CreatedAt",
    UpdatedAt: "UpdatedAt",
    RoleName: "RoleName",
    RolePriority: "RolePriority",
} as const;
