/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */
import type { Role } from "./role";
import type { Uuid } from "./uuid";

export interface User {
    id: Uuid;
    nickname: string;
    last_access: string;
    created_at: string;
    updated_at: string;
    role: Role;
}
