// Code generated by permission/codegen; DO NOT EDIT

package permission

var Admin = Permission{
	ID:           1,
	Name:         "admin",
	DefaultValue: false,
}

var UserList = Permission{
	ID:           2,
	Name:         "user.list",
	DefaultValue: false,
}

var UserCreate = Permission{
	ID:           3,
	Name:         "user.create",
	DefaultValue: false,
}

var UserEditNickname = Permission{
	ID:           4,
	Name:         "user.edit.nickname",
	DefaultValue: false,
}

var UserDelete = Permission{
	ID:           5,
	Name:         "user.delete",
	DefaultValue: false,
}

var MypageView = Permission{
	ID:           6,
	Name:         "mypage.view",
	DefaultValue: true,
}

var MypageEditNickname = Permission{
	ID:           7,
	Name:         "mypage.edit.nickname",
	DefaultValue: true,
}

var RoleList = Permission{
	ID:           8,
	Name:         "role.list",
	DefaultValue: false,
}
