/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * Monitor API
 * OpenAPI spec version: 0.0.0
 */

import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";
import { useMutation, useQuery } from "@tanstack/react-query";

import type {
    AccessTokenWithMeAndPagePermissions,
    CurrentPage,
    GoogleLoginURL,
} from "../model";

/**
 * Callback from Google
 */
export type callbackFromGoogleResponse307 = {
    data: void;
    status: 307;
};

export type callbackFromGoogleResponse406 = {
    data: void;
    status: 406;
};
export type callbackFromGoogleResponseError = (
    | callbackFromGoogleResponse307
    | callbackFromGoogleResponse406
) & {
    headers: Headers;
};

export type callbackFromGoogleResponse = callbackFromGoogleResponseError;

export const getCallbackFromGoogleUrl = () => {
    return `/auth/google/callback`;
};

export const callbackFromGoogle = async (
    options?: RequestInit,
): Promise<callbackFromGoogleResponse> => {
    const res = await fetch(getCallbackFromGoogleUrl(), {
        ...options,
        method: "GET",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: callbackFromGoogleResponse["data"] = body
        ? JSON.parse(body)
        : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as callbackFromGoogleResponse;
};

export const getCallbackFromGoogleQueryKey = () => {
    return [`/auth/google/callback`] as const;
};

export const getCallbackFromGoogleQueryOptions = <
    TData = Awaited<ReturnType<typeof callbackFromGoogle>>,
    TError = void,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof callbackFromGoogle>>,
            TError,
            TData
        >
    >;
    fetch?: RequestInit;
}) => {
    const { query: queryOptions, fetch: fetchOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getCallbackFromGoogleQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof callbackFromGoogle>>
    > = ({ signal }) => callbackFromGoogle({ signal, ...fetchOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof callbackFromGoogle>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CallbackFromGoogleQueryResult = NonNullable<
    Awaited<ReturnType<typeof callbackFromGoogle>>
>;
export type CallbackFromGoogleQueryError = void;

export function useCallbackFromGoogle<
    TData = Awaited<ReturnType<typeof callbackFromGoogle>>,
    TError = void,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof callbackFromGoogle>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof callbackFromGoogle>>,
                    TError,
                    Awaited<ReturnType<typeof callbackFromGoogle>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCallbackFromGoogle<
    TData = Awaited<ReturnType<typeof callbackFromGoogle>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof callbackFromGoogle>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof callbackFromGoogle>>,
                    TError,
                    Awaited<ReturnType<typeof callbackFromGoogle>>
                >,
                "initialData"
            >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCallbackFromGoogle<
    TData = Awaited<ReturnType<typeof callbackFromGoogle>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof callbackFromGoogle>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useCallbackFromGoogle<
    TData = Awaited<ReturnType<typeof callbackFromGoogle>>,
    TError = void,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof callbackFromGoogle>>,
                TError,
                TData
            >
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getCallbackFromGoogleQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * First login with Google Account
 */
export type linkWithGoogleResponse200 = {
    data: GoogleLoginURL;
    status: 200;
};

export type linkWithGoogleResponse406 = {
    data: void;
    status: 406;
};

export type linkWithGoogleResponseSuccess = linkWithGoogleResponse200 & {
    headers: Headers;
};
export type linkWithGoogleResponseError = linkWithGoogleResponse406 & {
    headers: Headers;
};

export type linkWithGoogleResponse =
    | linkWithGoogleResponseSuccess
    | linkWithGoogleResponseError;

export const getLinkWithGoogleUrl = (loginKey: string) => {
    return `/auth/google/link/${loginKey}`;
};

export const linkWithGoogle = async (
    loginKey: string,
    options?: RequestInit,
): Promise<linkWithGoogleResponse> => {
    const res = await fetch(getLinkWithGoogleUrl(loginKey), {
        ...options,
        method: "POST",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: linkWithGoogleResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as linkWithGoogleResponse;
};

export const getLinkWithGoogleMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof linkWithGoogle>>,
        TError,
        { loginKey: string },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof linkWithGoogle>>,
    TError,
    { loginKey: string },
    TContext
> => {
    const mutationKey = ["linkWithGoogle"];
    const { mutation: mutationOptions, fetch: fetchOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof linkWithGoogle>>,
        { loginKey: string }
    > = (props) => {
        const { loginKey } = props ?? {};

        return linkWithGoogle(loginKey, fetchOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type LinkWithGoogleMutationResult = NonNullable<
    Awaited<ReturnType<typeof linkWithGoogle>>
>;

export type LinkWithGoogleMutationError = void;

export const useLinkWithGoogle = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof linkWithGoogle>>,
            TError,
            { loginKey: string },
            TContext
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof linkWithGoogle>>,
    TError,
    { loginKey: string },
    TContext
> => {
    return useMutation(getLinkWithGoogleMutationOptions(options), queryClient);
};
/**
 * Login with Google Account
 */
export type loginWithGoogleResponse200 = {
    data: GoogleLoginURL;
    status: 200;
};

export type loginWithGoogleResponse406 = {
    data: void;
    status: 406;
};

export type loginWithGoogleResponseSuccess = loginWithGoogleResponse200 & {
    headers: Headers;
};
export type loginWithGoogleResponseError = loginWithGoogleResponse406 & {
    headers: Headers;
};

export type loginWithGoogleResponse =
    | loginWithGoogleResponseSuccess
    | loginWithGoogleResponseError;

export const getLoginWithGoogleUrl = () => {
    return `/auth/google/login`;
};

export const loginWithGoogle = async (
    currentPage: CurrentPage,
    options?: RequestInit,
): Promise<loginWithGoogleResponse> => {
    const res = await fetch(getLoginWithGoogleUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(currentPage),
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: loginWithGoogleResponse["data"] = body ? JSON.parse(body) : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as loginWithGoogleResponse;
};

export const getLoginWithGoogleMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof loginWithGoogle>>,
        TError,
        { data: CurrentPage },
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof loginWithGoogle>>,
    TError,
    { data: CurrentPage },
    TContext
> => {
    const mutationKey = ["loginWithGoogle"];
    const { mutation: mutationOptions, fetch: fetchOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof loginWithGoogle>>,
        { data: CurrentPage }
    > = (props) => {
        const { data } = props ?? {};

        return loginWithGoogle(data, fetchOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type LoginWithGoogleMutationResult = NonNullable<
    Awaited<ReturnType<typeof loginWithGoogle>>
>;
export type LoginWithGoogleMutationBody = CurrentPage;
export type LoginWithGoogleMutationError = void;

export const useLoginWithGoogle = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof loginWithGoogle>>,
            TError,
            { data: CurrentPage },
            TContext
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof loginWithGoogle>>,
    TError,
    { data: CurrentPage },
    TContext
> => {
    return useMutation(getLoginWithGoogleMutationOptions(options), queryClient);
};
/**
 * Invalidate refresh_token and access_token
 */
export type logoutResponse204 = {
    data: void;
    status: 204;
};

export type logoutResponse401 = {
    data: void;
    status: 401;
};

export type logoutResponseSuccess = logoutResponse204 & {
    headers: Headers;
};
export type logoutResponseError = logoutResponse401 & {
    headers: Headers;
};

export type logoutResponse = logoutResponseSuccess | logoutResponseError;

export const getLogoutUrl = () => {
    return `/auth/logout`;
};

export const logout = async (
    options?: RequestInit,
): Promise<logoutResponse> => {
    const res = await fetch(getLogoutUrl(), {
        ...options,
        method: "POST",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: logoutResponse["data"] = body ? JSON.parse(body) : {};
    return { data, status: res.status, headers: res.headers } as logoutResponse;
};

export const getLogoutMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = ["logout"];
    const { mutation: mutationOptions, fetch: fetchOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof logout>>,
        void
    > = () => {
        return logout(fetchOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type LogoutMutationResult = NonNullable<
    Awaited<ReturnType<typeof logout>>
>;

export type LogoutMutationError = void;

export const useLogout = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof logout>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof logout>>,
    TError,
    void,
    TContext
> => {
    return useMutation(getLogoutMutationOptions(options), queryClient);
};
/**
 * Refresh access token
 */
export type refreshAccessTokenResponse200 = {
    data: AccessTokenWithMeAndPagePermissions;
    status: 200;
};

export type refreshAccessTokenResponse401 = {
    data: void;
    status: 401;
};

export type refreshAccessTokenResponseSuccess =
    refreshAccessTokenResponse200 & {
        headers: Headers;
    };
export type refreshAccessTokenResponseError = refreshAccessTokenResponse401 & {
    headers: Headers;
};

export type refreshAccessTokenResponse =
    | refreshAccessTokenResponseSuccess
    | refreshAccessTokenResponseError;

export const getRefreshAccessTokenUrl = () => {
    return `/auth/refresh`;
};

export const refreshAccessToken = async (
    options?: RequestInit,
): Promise<refreshAccessTokenResponse> => {
    const res = await fetch(getRefreshAccessTokenUrl(), {
        ...options,
        method: "POST",
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();

    const data: refreshAccessTokenResponse["data"] = body
        ? JSON.parse(body)
        : {};
    return {
        data,
        status: res.status,
        headers: res.headers,
    } as refreshAccessTokenResponse;
};

export const getRefreshAccessTokenMutationOptions = <
    TError = void,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof refreshAccessToken>>,
        TError,
        void,
        TContext
    >;
    fetch?: RequestInit;
}): UseMutationOptions<
    Awaited<ReturnType<typeof refreshAccessToken>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = ["refreshAccessToken"];
    const { mutation: mutationOptions, fetch: fetchOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, fetch: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof refreshAccessToken>>,
        void
    > = () => {
        return refreshAccessToken(fetchOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type RefreshAccessTokenMutationResult = NonNullable<
    Awaited<ReturnType<typeof refreshAccessToken>>
>;

export type RefreshAccessTokenMutationError = void;

export const useRefreshAccessToken = <TError = void, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof refreshAccessToken>>,
            TError,
            void,
            TContext
        >;
        fetch?: RequestInit;
    },
    queryClient?: QueryClient,
): UseMutationResult<
    Awaited<ReturnType<typeof refreshAccessToken>>,
    TError,
    void,
    TContext
> => {
    return useMutation(
        getRefreshAccessTokenMutationOptions(options),
        queryClient,
    );
};
