name: App CI
on:
  push:
    paths: [ 'app/**', '.github/workflows/app_ci.yml' ]
  pull_request:
    paths: [ 'app/**', '.github/workflows/app_ci.yml' ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    services:
      mariadb:
        image: mariadb:12.3.3@sha256:dd9b303aed4f4890ed09f766d8ca9ddfd176c0c6f6267feff53b3192ec65a979
        ports:
          - "3306:3306"
        env:
          MYSQL_DATABASE: monitor_db
          MYSQL_ROOT_PASSWORD: monitor_pw
        options: >-
          --health-cmd "healthcheck.sh --connect --innodb_initialized"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      MONITOR_DB_HOST: 127.0.0.1
      MONITOR_DB_PORT: 3306
      MONITOR_DB_USER: root
      MONITOR_DB_PASSWORD: monitor_pw
      MONITOR_DB_NAME: monitor_db
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: |
            app
            schema/database
      - name: "Set up Go"
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: app/go.mod
          cache: true
          cache-dependency-path: |
            app/go.sum
      - name: "Build"
        run: go build cmd/http/main.go
      - name: "Run test"
        run: go run gotest.tools/gotestsum@v1.12.3 --junitfile ~/test-results.xml
      - name: "Upload Results"
        uses: mikepenz/action-junit-report@a9170d5795813c01ab4901ffb045b52bab4ab09d # v6.5.0
        if: ${{ success() || failure() }}
        continue-on-error: true
        with:
          report_paths: ~/test-results.xml
          check_name: Test Report
